# This is a basic workflow to heslp yosu get sfftartedf with Actionssdfssdf

name: SQL Checker

on:
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: RUN SQLCheck

    steps:

      - name: Checkout Master Branch
        uses: actions/checkout@v2
        id: mastersource
        with:
          ref: master
        run: |
          cd ./Common/src/main/sql/iris/migration/2020/2020
          echo ::set-output name=MASTERSOURCE::$(ls)

      - name: Checkout Current Branch
        uses: actions/checkout@v2
        id: currentsource
        run: |
          cd ./Common/src/main/sql/iris/migration/2020/2020
          echo ::set-output name=CURRENTSOURCE::$(ls)

      - name: Read GitHub Workspace
        uses: NathanNorman/nnorman-test@v1
        with:
          master_sql: ${{ steps.mastersource.outputs.MASTERSOURCE }}
          current_sql: ${{ steps.mastersource.outputs.CURRENTSOURCE }}


