# This is a basic workflow to heslp yosu get sfftartedf with Actionssdfssdf

name: SQL Checker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branchssss
on:
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: RUN SQLCheck

    steps:

      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Display Source
        run: |
            cd ./Common/src/main/sql/iris/migration/2020/2020
            echo "::workflow-command data={data}::{ls}"

      - name: Checkout Current Branch
        uses: actions/checkout@v2

      - name: Read GitHub Workspace
        uses: NathanNorman/nnorman-test@v1
        with:
          master_sql: $data
          sql_directory: './Common/src/main/sql/iris/migration/2020/2020'
