# This is a basic workflow to heslp yosu get sfftartedf with Actionssdfssdf

name: SQL Checker

on:
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: RUN SQLCheck

    steps:

      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Display Source
        id: mastersource
        run: |
            cd ./Common/src/main/sql/iris/migration/2020/2020
            echo ::set-output name=MASTERSOURCE::$(ls)


      - name: Checkout Current Branch
        uses: actions/checkout@v2

      - name: Read GitHub Workspace
        uses: NathanNorman/nnorman-test@v1
        with:
          master_sql: $MASTERSOURCE
          sql_directory: './Common/src/main/sql/iris/migration/2020/2020'


